### ISSUE TITLE
поправки на будущее в путях и ссылках

### ISSUE THREAD

**Issue by cjbars** [Student201562/Web-game#4]
не желательно делать следующие вещи
- пробелы в путях `src="images/heisenberg (1).png"`
- русские символы в путях `background-image: url(../images/диабло.jpg);`
- в реальной жизни сервера могут быть чувствительны к CamelCaseNames, лучше все делать маленькими буквами `startgame.html или start_game.html вместо StartGame.html`

**Comment by Student201562** [comment]
Выполнил
